# Generated by Django 5.2.6 on 2025-09-25 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Energie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prix", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Localisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("taxes", models.FloatField()),
                ("prix_m2", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="MatierePremiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("stock", models.FloatField()),
                ("emprise", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="DebitEnergie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debit", models.FloatField()),
                (
                    "energie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="high_level.energie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("surface", models.FloatField()),
                (
                    "localisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="high_level.localisation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="energie",
            name="localisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="high_level.localisation",
            ),
        ),
    ]
